# Generated by Django 5.0.2 on 2024-03-06 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Title')),
                ('type', models.CharField(max_length=32, verbose_name='Type')),
                ('sub_type', models.CharField(max_length=32, verbose_name='Sub Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('configuration_template', models.TextField(verbose_name='Configuration Template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Title')),
                ('configuration_data', models.TextField(verbose_name='Configuration Data')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('last_connected_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last Connected')),
                ('log_message', models.TextField(blank=True, null=True, verbose_name='Log message')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quickstart.application', verbose_name='Application')),
            ],
        ),
    ]
